all:
	g++ --std=c++17 -I/Users/cpwang/Programs/git/embree/include -I/Users/cpwang/Programs/git/glfw/include -o minimal -L/Users/cpwang/Programs/git/embree/build -L/Users/cpwang/Programs/git/glfw/glfw-build-3.3/src -lembree -framework OpenGL -lglfw3 -framework Cocoa -framework CoreVideo -framework IOKit minimal.cc
